### ISSUE TITLE
Find in text

### ISSUE THREAD

**Issue by elcste** [agateau/nanonote#16]
This may be something that turns nanonote into micronote, so I understand if you reject the idea ;-)

Even with such a simple notes app, I sometimes wish there was a find command to locate certain text. I can copy and paste into a text editor, but it would be nice not to have to. Maybe you could use some of the code from the new Falkon find bar (https://phabricator.kde.org/D19625)?

**Comment by agateau** [comment]
I think it can fit in Nanonote, will look into it when I find time for the project again :)

**Comment by pavol47** [comment]
I would like to work on this.

**Comment by agateau** [comment]
Great! What do you need to get started? Have you build nanonote?

**Comment by pavol47** [comment]
I don´t need anything to get started. I built nanonote successfully. If I have any questions so I will contact you.

**Comment by pavol47** [comment]
I sent pull request for this issue.

**Comment by agateau** [comment]
Thanks to @pavol47, this is done!
