### ISSUE TITLE
Press enter a second time to remove automatic list bullet

### ISSUE THREAD

**Issue by elcste** [agateau/nanonote#2]
Sometimes you want to quickly get out of the auto-bullet list. One way to do this is to remove the automatic list bullet if you press enter a second time. Both Google Keep and Notational Velocity (a Mac notes app) have this feature, and it's pretty nice once you get used to it.

**Comment by agateau** [comment]
Sounds like a good idea, will look into it.

**Comment by agateau** [comment]
Just implemented it
