### ISSUE TITLE
WISH: Color customization

### ISSUE THREAD

**Issue by thegreyshadow** [agateau/nanonote#22]
Aurelien, thanks for nanonote. It looks great and useful.

I know this would be cumbersome to implement it, but it would be nice if we could set nanonote's background and text foreground colors. I now have a light theme but I would like to have nanonte in a dark theme, with black background and some color such as green or orange as text foreground.

Thanks again!

**Comment by agateau** [comment]
I am sorry but that would be a slippery slope which would lead to things like skin support. I don't want to go that way.

You can take advantage of Qt stylesheet system to workaround this though:

Create a file named dark.css with the following content:

```css
QPlainTextEdit {
    background-color: #232629;
    color: #eff0f1;
}
```

Now start nanonote like this: `nanonote -stylesheet dark.css`. You should get a dark Nanonote main window (note that unfortunately you can't set the link colors through stylesheets)
