### ISSUE TITLE
Indent not working for last line when multiple lines are selected

### ISSUE THREAD

**Issue by dani-l** [agateau/nanonote#3]
When selecting multiple lines and pressing Ctrl+I (or now Tab :smile:), the last line is not indented unless the final newline is also part of the selection. The same happens for unindenting.

I would hope for a behavior similar to Kate: The last line of the selection should be (un-)indented as soon as at least one character of the line is part of the selection.

**Comment by dani-l** [comment]
I just noticed #6, which describes the same issue. With the current master branch, I could not reproduce the issue anymore. Unfortunately, I didn't test enough to notice that only upward selections are affected, so I'm sorry if my description was not too helpful.

**Comment by agateau** [comment]
Great to hear, thanks for the added details.
