### ISSUE TITLE
Upward selection weirdly indented

### ISSUE THREAD

**Issue by tmonjalo** [agateau/nanonote#6]
If selecting a text in upper direction, and indenting, there are strange behaviors:
- if the first line of the selection is fully selected, the last line won't be indented on first tab
- if the selection is initiated from the beginning of a line, this line will be part of the selection

There is no such strange behavior with a downward selection 

Reproduction steps from an empty note:
```
    a
    <return>
    b
    <left>
    <shift> + <up>
    <tab>
    <tab>
```

Expected:
- "a" should be indented two times
- "b" should not be indented (not selected)

Seen:
- "a" is indented two times (fine)
- "b" is indented on second time

Version: 07c2b0c

**Comment by agateau** [comment]
Indeed! Going to look into this.

**Comment by tmonjalo** [comment]
I confirm it is fixed. Thanks!
