### ISSUE TITLE
Full source package

### ISSUE THREAD

**Issue by dragotin** [agateau/nanonote#62]
I am trying to build a package in the openSUSE buildservice for the openSUSE distros, but the sourcepackage you provide does not have the thirdparty sources included.

It would be way easier if you would add the sources to your tarball.

The more advanced way would be if you made it optional to use Catch2 from the system, as that is available as package.  For the single app source I would still suggest to add it.

**Comment by agateau** [comment]
have you tried this one: https://github.com/agateau/nanonote/releases/download/1.4.0/nanonote-1.4.0.tar.bz2? It should be complete.

**Comment by agateau** [comment]
Assuming it's OK.
