### ISSUE TITLE
Feature Request: Monitor External File for Changes

### ISSUE THREAD

**Issue by BeatLink** [agateau/nanonote#65]
Hey, It would be great if nanonote could monitor its external file for any changes and load the new content, so that it could be used to sync notes between different devices

**Comment by agateau** [comment]
Hi, sorry for the late reply.

I am not sure I want to dive into that, because doing it well means handling conflicts, and that feels too complicated for a minimalist note taking app.

**Comment by BeatLink** [comment]
Okay no prob. Thanks
