### ISSUE TITLE
Inline asterisk * misrepresented as '

### ISSUE THREAD

**Issue by grahamperrin** [agateau/nanonote#70]
For example, pasted: 

![image](https://github.com/agateau/nanonote/assets/192271/a138fc28-ebe9-43d7-a53f-c070de5f58bf)

```text
% pkg iinfo nanonote
nanonote-1.4.0
% uname -aKU
FreeBSD mowa219-gjp4-8570p-freebsd 15.0-CURRENT FreeBSD 15.0-CURRENT #14 main-n265350-72d97e1dd9cc-dirty: Sat Sep 16 03:50:44 BST 2023     grahamperrin@mowa219-gjp4-8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64 1500000 1500000
% 
```

<https://www.freshports.org/deskutils/nanonote/> (ported to FreeBSD).

**Comment by agateau** [comment]
This is very odd, I can't reproduce it. Can you attach the content of `$HOME/.local/share/agateau.com/nanonote/nanonote.txt` to this issue?

Does it do the same if you use another font?

**Comment by vkarlsen** [comment]
I can't reproduce either.
![image](https://github.com/agateau/nanonote/assets/256005/e5b319f5-bad0-458b-a5fd-98e7ef8cce9a)

**Comment by grahamperrin** [comment]
Thanks. So, this seems to be amongst recent issues with ports on FreeBSD but _not_, I think, an issue with the port of Nanonote. 

Apologies for the noise. I'll close, with these footnotes, and take discussion elsewhere. 

----

```text
% cat $HOME/.local/share/agateau.com/nanonote/nanonote.txt
    Option         "UseEdidDpi" "FALSE"
    
Ellipsis … 

Inline * asterisk% 
```

I experimented with a change from Steps Mono 10 to (overly large) Victor Mono 14, quit then reopened Nanonote, no change: 

![image](https://github.com/agateau/nanonote/assets/192271/7f1e0a48-05f9-447d-8663-cc2b2f92e4c0)

* ellipsis is OK
* asterisk remains bugged.

I sometimes see an ellipsis `…` misrepresented as a full stop `.` in Thunderbird, I have not yet got to the root of this bug.
